Add missing reorder_img import
This was causing 'from nilearn.image import *' to fail with
AttributeError: 'module' object has no attribute 'reorder_img'