[FIX] LGTM error: Too few arguments in formatting call
Too few arguments for string format. Format
"X has {} features per sample; expecting {}"
requires at least 2, but 1 is provided.