[FIX] LGTM errors (#2919)
* [FIX] LGTM error: Unused exception object

Instantiating an exception, but not raising it, has no effect

* [FIX] LGTM error: Too few arguments in formatting call

Too few arguments for string format. Format
"X has {} features per sample; expecting {}"
requires at least 2, but 1 is provided.

* [FIX] LGTM error: Explicit export is not defined

The name 'stats' is exported by __all__ but is not defined.
The name 'parcellations' is exported by __all__ but is not defined.

* [FIX] LGTM error: Redundant assignment

This assignment assigns a variable to itself.

* [FIX] LGTM error: Wrong number of arguments for format

Wrong number of arguments for string format.
Format %n contrasts given, while there are %n runs
takes 0, but 2 are provided.

There is no such thing as a "%n" conversion type.

* [FIX] LGTM error: Redundant assignment

This assignment assigns a variable to itself.

* [FIX] LGTM error: Wrong name for an argument in a class instantiation

Keyword argument 'mask' is not a supported parameter name of
SecondLevelModel.__init__.

* [FIX] LGTM error: Non-callable called

Call to a non-callable of builtin-class str.

Read this if you need to make complete sense of this error:
https://github.com/github/codeql/issues/6491#issuecomment-900248431